### ISSUE TITLE
Use of 90% CI

### ISSUE THREAD

**Issue by larsvilhuber** [larsvilhuber/MobZ#2]
Mark writes: "Census uses 1.645 for 90% confidence intervals, not 1.64 (as in the current code). Not a reason to re-run right now, but we should use 1.645 for any revision (and make it a macro parameter).
https://www2.census.gov/programs-surveys/acs/tech_docs/accuracy/MultiyearACSAccuracyofData2010.pdf"

**Comment by andrewfoote** [comment]
Updated programs to reflect this change (as a macro in analysis_ctrl.sas now)
